import {build} from 'esbuild';
import {mkdir,copyFile,cp,rm,readFile,writeFile} from 'node:fs/promises';
import {createHash} from 'node:crypto';
import {resolve} from 'node:path';
const hash=bytes=>createHash('sha256').update(bytes).digest('hex').slice(0,12);
await mkdir('public/vendor/onnx',{recursive:true});
for(const file of ['ort-wasm-simd-threaded.wasm','ort-wasm-simd-threaded.mjs','ort-wasm-simd-threaded.jsep.wasm','ort-wasm-simd-threaded.jsep.mjs'])await copyFile('node_modules/onnxruntime-web/dist/'+file,'public/vendor/onnx/'+file);
await build({entryPoints:['public/semantic-worker.mjs'],outfile:'public/worker.js',bundle:true,format:'esm',platform:'browser',minify:true});
await rm('dist',{recursive:true,force:true});await mkdir('dist',{recursive:true});
const workerName='worker-'+hash(await readFile('public/worker.js'))+'.js';
await copyFile('public/worker.js','dist/'+workerName);
const source=(await readFile('public/app.js','utf8')).replace('./worker.js','./'+workerName);
const app=await build({stdin:{contents:source,resolveDir:resolve('public'),sourcefile:'app.js'},bundle:true,format:'esm',platform:'browser',target:'es2022',minify:true,write:false});
const appName='app-'+hash(app.outputFiles[0].contents)+'.js';
await writeFile('dist/'+appName,app.outputFiles[0].contents);
const html=(await readFile('public/index.html','utf8')).replace('./app.js','./'+appName).replace('./style.css','./style.css?v='+hash(await readFile('public/style.css')));
await writeFile('dist/index.html',html);
for(const file of ['favicon.ico','style.css'])await copyFile('public/'+file,'dist/'+file);
for(const dir of ['models','data','vendor','licenses','recording-previews'])await cp('public/'+dir,'dist/'+dir,{recursive:true});
await copyFile('source-manifest.json','dist/source-manifest.json');
await copyFile('public/THIRD_PARTY_NOTICES.txt','dist/THIRD_PARTY_NOTICES.txt');
await copyFile('model-manifest.json','dist/model-manifest.json');
if(!process.argv.includes('--embedded'))await writeFile('dist/CNAME','search.eecs245.org\n');await writeFile('dist/.nojekyll','');
console.log('Static deployment built in dist/');
