import {build} from 'esbuild';
import {mkdir,copyFile,cp,rm,readFile,writeFile} from 'node:fs/promises';
await mkdir('public/vendor/onnx',{recursive:true});
for(const file of ['ort-wasm-simd-threaded.wasm','ort-wasm-simd-threaded.mjs','ort-wasm-simd-threaded.jsep.wasm','ort-wasm-simd-threaded.jsep.mjs'])await copyFile('node_modules/onnxruntime-web/dist/'+file,'public/vendor/onnx/'+file);
await build({entryPoints:['public/semantic-worker.mjs'],outfile:'public/worker.js',bundle:true,format:'esm',platform:'browser',minify:true});
await rm('dist',{recursive:true,force:true});await mkdir('dist',{recursive:true});
for(const file of ['index.html','favicon.ico','style.css','app.js','search.mjs','query.mjs','worker.js'])await copyFile('public/'+file,'dist/'+file);
for(const dir of ['models','data','vendor','licenses'])await cp('public/'+dir,'dist/'+dir,{recursive:true});
await copyFile('source-manifest.json','dist/source-manifest.json');
await copyFile('public/THIRD_PARTY_NOTICES.txt','dist/THIRD_PARTY_NOTICES.txt');
await copyFile('model-manifest.json','dist/model-manifest.json');
if(!process.argv.includes('--embedded'))await writeFile('dist/CNAME','search.eecs245.org\n');await writeFile('dist/.nojekyll','');
console.log('Static deployment built in dist/');
